import { AuroraDSQLPool, isOCCError } from "@aws/aurora-dsql-node-postgres-connector";

/**
 * Aurora DSQL connection pool. Uses IAM auth (token generated by the connector)
 * with AWS credentials from the environment — locally from .env.local, on Vercel
 * from project env vars. For production keyless, swap in the Vercel OIDC
 * credentials provider (see README).
 */
const pool = new AuroraDSQLPool({
  host: process.env.PGHOST!,
  region: process.env.AWS_REGION!,
  user: process.env.PGUSER || "admin",
  database: process.env.PGDATABASE || "postgres",
  port: Number(process.env.PGPORT || 5432),
});

export async function query<T = any>(sql: string, args: unknown[] = []): Promise<T[]> {
  const r = await pool.query(sql, args as any[]);
  return r.rows as T[];
}

export async function withConnection<T>(fn: (client: any) => Promise<T>): Promise<T> {
  const client = await (pool as any).connect();
  try {
    return await fn(client);
  } finally {
    client.release();
  }
}

/** Run `fn` and retry on Aurora DSQL OCC conflicts (SQLSTATE 40001 / OC000). */
export async function withOCCRetry<T>(fn: () => Promise<T>, maxAttempts = 5): Promise<T> {
  const r = await withOCCRetryCounted(fn, maxAttempts);
  return r.value;
}

/**
 * Same as withOCCRetry, but reports how many OCC retries the call survived.
 * Exposed so the stress-test endpoint can show judges a *measured* OCC signal
 * (e.g. "5 concurrent appends → N retries, no gaps") rather than asserting it.
 */
export async function withOCCRetryCounted<T>(fn: () => Promise<T>, maxAttempts = 5): Promise<{ value: T; retries: number }> {
  let retries = 0;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      const value = await fn();
      return { value, retries };
    } catch (e: any) {
      if (
        isOCCError(e) ||
        /40001|OC000|could not serialize|concurrent update|duplicate key|23505|unique constraint/i.test(
          String(e?.message || e),
        )
      ) {
        retries++;
        await new Promise((r) => setTimeout(r, 50 * 2 ** attempt + Math.random() * 30));
        continue;
      }
      throw e;
    }
  }
  throw new Error("OCC retry exhausted");
}
